test: usage trace api cnf icnf mbt
api:
	@echo "Running API tests"
	@api/run.sh
cnf:
	@echo "Running CNF tests"
	@cnf/run.sh
icnf:
	@echo "Running ICNF tests"
	@icnf/run.sh
mbt:
	@echo "Running MBT tests"
	@mbt/run.sh
trace:
	@echo "Running trace tests"
	@trace/run.sh
usage:
	@echo "Running usage tests"
	@usage/run.sh
.PHONY: test api cnf icnf mbt trace usage
